export const UPDATE_EXPERIENCES = "UPDATE_EXPERIENCES";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CART_POINTS = "UPDATE_CART_POINTS";
export const UPDATE_USER_POINTS = "UPDATE_USER_POINTS";

export const UPDATE_ACTIVITY_LEVEL = "UPDATE_ACTIVITY_LEVEL";
export const UPDATE_CURRENT_ACTIVITY_LEVEL = "UPDATE_CURRENT_ACTIVITY_LEVEL";